import '/public/output.css'
import 'swiper/element/css/effect-coverflow'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Yumi Chen',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="preload"
          href="/output.css"
          as="stylesheet"
        />
      </Head>
      <body 
        className={`${inter.className} bg-teal-400 overflow-hidden w-screen h-[100dvh]`}
      >{children}</body>
    </html>
  )
}
