"use client";

import '/public/output.css'
import 'swiper/element/css/effect-coverflow'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Yumi Chen',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [displayPage, setDisplayPage] = useState(false);

  return (
    <html lang="en">
      <Head>
        <link
          rel="preload"
          href="/output.css"
          as="stylesheet"
        />
      </Head>
      <body 
        className={`${displayPage? 'opacity-100 pointer-events-auto' : 'opacity-0 pointer-events-none'} transition-opacity duration-500 ${inter.className} bg-teal-400 overflow-hidden w-screen h-[100dvh]`}
        onLoad={()=>{
          setDisplayPage(true);
        }}
      >{children}</body>
    </html>
  )
}
