import '/public/output.css'
import 'swiper/element/css/effect-coverflow'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Yumi Chen',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body 
        className={`${inter.className} bg-teal-400 overflow-hidden w-screen h-screen`}
      >{children}</body>
    </html>
  )
}
